# 데이터 분석 패키지(라이브러리)

*   Numpy: 다차원 배열을 쉽게 사용할 수 있도록 만들어진 패키지. 머신러닝에서 중요하게 사용됨.
*   pandas: 시리즈(Series)와 데이터프레임(DataFrame)을 기본으로 사용해서 데이터 분석에 필요한 기능들을 가지고 있는 패키지.
*   matplotlib, seaborn: 데이터 시각화(그래프)
*   scikit-learn: 머신러닝(Machine Learning) 패키지.
*   keras: 딥러닝(Deep Learning) 패키지.

In [1]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
import sklearn  # scikit-learn 패키지
import keras

In [2]:
print("numpy version =", np.__version__)
print("pandas version =", pd.__version__)
print("matplotlib version =", matplotlib.__version__)
print("seaborn version =", sns.__version__)
print("sklearn version =", sklearn.__version__)
print("keras version =", keras.__version__)

numpy version = 2.0.2
pandas version = 2.2.2
matplotlib version = 3.10.0
seaborn version = 0.13.2
sklearn version = 1.6.1
keras version = 3.10.0


# Python `list` 클래스

*   여러개의 값들을 저장할 수 있는 데이터 타입.
*   인덱스를 기반으로 한 데이터 타입.
    *   indexing: 인덱스를 사용해서 리스트의 특정 위치의 값을 참조. (예) `list[0]`
    *   slicing: [start, end) 인덱스 범위의 리스트를 잘라냄. (예) `list[0:5]`
*   산술 연산
    *   `list + list`: concatenate. 리스트 이어붙이기.
    *   `list * int, int * list`: replicate. 리스트의 원소들을 정수만큼 복사.

In [3]:
numbers1 = [1, 2, 3]
numbers2 = [11, 22, 33]

In [4]:
print(numbers1)

[1, 2, 3]


In [5]:
numbers2

[11, 22, 33]

In [6]:
# indexing
print(numbers1[0])  # 리스트의 첫번째 원소
print(numbers1[-1])  # 리스트의 마지막 원소

1
3


In [7]:
# slicing
print(numbers2[:2]) # 리스트에서 첫 2개 원소들을 잘라내기
print(numbers2[-2:])  # 리스트에서 마지막 2개 원소들을 잘라내기

[11, 22]
[22, 33]


In [8]:
numbers1 + numbers2

[1, 2, 3, 11, 22, 33]

In [9]:
numbers1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 덧셈 --> 결과 [1+11, 2+22, 3+33]
[x + y for x, y in zip(numbers1, numbers2)]

[12, 24, 36]

In [11]:
# numbers1의 모든 원소에 3을 곱함. --> 결과 [1*3, 2*3, 3*3]
[x * 3 for x in numbers1]

[3, 6, 9]

In [12]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 곱셈 --> [1*11, 2*22, 3*33]
[x * y for x, y in zip(numbers1, numbers2)]

[11, 44, 99]

# Numpy(Numerical Python)

*   다차원배열(n-dimensional array)을 쉽고 빠르게 연산(`+, -, *, /, ...`)하기 위한 패키지.
*   numpy 패키지의 대부분의 기능들(연산자, 함수, 메서드 등)은 반복문의 기능을 가지고 있음.
    *   같은 인덱스의 원소들끼리(element-wise) 연산하는 기능을 가지고 있음.
*   `numpy.ndarray` 클래스: numpy 패키지의 가장 기본이 되는 클래스.

In [13]:
num_array1 = np.array([1, 2, 3, 4, 5])

In [14]:
type(num_array1)

numpy.ndarray

In [15]:
print(num_array1)  # 리스트와 달리 원소와 원소 사이에 `,` 가 없음
# ndarray 클래스의 __str__() 메서드가 리턴하는 문자열을 출력

[1 2 3 4 5]


In [16]:
num_array1  # ndarray 클래스의 __repr__() 메서드가 리턴하는 문자열을 출력

array([1, 2, 3, 4, 5])

In [17]:
num_array2 = np.array([10, 20, 30, 40, 50])

In [18]:
# element-wise(같은 인덱스의 원소들끼리) 연산
print(num_array1 + num_array2)  # [1+10, 2+20, 3+30, ...]
print(num_array1 - num_array2)  # [1-10, 2-20, 3-30, ...]
print(num_array1 * num_array2)  # [1*10, 2*20, 3*30, ...]
print(num_array1 * 3)
print(num_array1 / num_array2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[ 3  6  9 12 15]
[0.1 0.1 0.1 0.1 0.1]


# `np.ndarray` 클래스의 속성들(attributes)

In [22]:
print(num_array1)
print('ndim =', num_array1.ndim)  # number of dimension(차원의 개수)
print('size =', num_array1.size)  # 배열의 크기
print('shape =', num_array1.shape)  # 배열의 모양(배열의 각 차원의 원소 개수들로 이루어진 튜플)
print('dtype =', num_array1.dtype)  # data type(배월 원소의 데이터 타입)

[1 2 3 4 5]
ndim = 1
size = 5
shape = (5,)
dtype = int64


*   Python의 숫자 타입
    *   정수: int
    *   실수: float
*   Numpy의 숫자 타입
    *   정수: int8, int16, int32, int64m ...
    *   실수: float16, float32, float64, ...

In [27]:
# 2차원 배열
array = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [28]:
print(array)
array

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print('ndim =', array.ndim)
print('size =', array.size)
print('shape =', array.shape)
print('dtype =', array.dtype)

ndim = 2
size = 6
shape = (2, 3)
dtype = int64


## `np.array(object)`

*   object를 ndarray로 변환해서 리턴.
*   object: 배열과 비슷한 객체들. list, tuple, ndarray, ...

In [31]:
# 0 이상 10 미만의 정수들로 이루어진 ndarray(배열)
numbers = np.array([x for x in range (10)])
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


## `np.arange(start, end, step)`

*   range를 사용해서 array(배열)을 만들어 주는 함수.
*   파이썬 `range(start, end, step)` 함수 사용법과 같음.
*   1차원 배열(ndarry)를 생성.

In [32]:
# 0 이상 10 미만의 정수들로 이루어진 ndarray(배열)
numbers = np.arange(10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
# 0 이상 10 미만의 짝수들로만 이루어진 배열
evens = np.arange(0, 10, 2)
print(evens)

[0 2 4 6 8]


## reshape

*   `np.reshape(array, newshape)` 함수(function)
*   `np.ndarray.reshape(newshape)` 메서드(method)

In [40]:
array = np.arange(12)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
# reshape 함수
array2 = np.reshape(array, (3, 4))
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [41]:
# reshape 메서드
array3 = array.reshape((4, 3))
print(array3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
# 함수(메서드) 연쇄 호출
array = np.arange(15).reshape((3, 5))
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### `np.random.rand(d0, d1, d2, ...)`

*   [0, 1) 범위의 균등분포(uniform distribution)를 따르는 난수들의 배열을 생성.
*   아규먼트(d0, d1, ...)들은 각 차원의 원소 개수.

In [43]:
array = np.random.rand(5)
print(array)

[0.79156453 0.45772102 0.69244041 0.56290841 0.68374718]


In [44]:
array = np.random.rand(3, 4)
print(array)

[[0.76801312 0.48801727 0.4393249  0.56858992]
 [0.25659775 0.44557963 0.83486477 0.89746103]
 [0.57482827 0.7909513  0.6533172  0.28931795]]


### `np.random.randn`(d0, d1, d2, ...)

*   평균이 0이고 표준편차가 1인 표준정규분포(standard normal distribution)를 따르는 난수들의 배열을 생성.
*   아규먼트들(d0, d1, ...)은 각 차원의 원소 개수.


In [45]:
array = np.random.randn(5)
print(array)

[-0.3203396   0.09704479 -1.55884615 -1.19383538  1.64699145]


In [47]:
array = np.random.randn(3, 5)
print(array)

[[-0.32955228  0.49364923  1.15579273  0.77944886 -0.29105329]
 [-0.56288268 -0.52579616 -0.14523159 -1.42006729  1.8412756 ]
 [-1.89691741  1.22800334 -1.05051011  1.73656027  1.87250226]]


### `np.random.randint(low, high, size, dtype)`

*   [low, high) 범위의 정수 난수들을 원소로 하는 배열을 생성.
*   파라미터 size: ndarray의 **shape**를 정수 또는 튜플로 전달.
*   파라미터 dtype: int8, int16, int32, int64, ...

In [48]:
array = np.random.randint(0, 10, size = 5)  # 파라미터 size에 정수를 전달 -> 1차원 배열
print(array)

[4 9 6 1 2]


In [50]:
array = np.random.randint(0, 10, size=(5,))  # shape이 (5,)인 1차원 배열
print(array)

[9 3 6 2 3]


In [51]:
array = np.random.randint(0, 10, size=(4, 5))  # shape이 (4, 5)인 2차원 배열
print(array)

[[2 8 3 8 9]
 [7 4 3 0 5]
 [6 8 6 0 7]
 [4 5 7 8 3]]


# 통계 함수/메서드

*   합계, 평균, 분산, 포준편차, 최댓값, 최솟값, ...
*   함수: `np.function_name(ndarray)`
*   메서드: `np.ndarray.method_name()`

In [52]:
array = np.random.randint(100, size=10)  # 0 이상 100 미만 10개의 정수 난수를 갖는 배열
print(array)

[10 56 98 13 91 78 48 86  5 27]


In [53]:
print('합계:', np.sum(array), array.sum())

합계: 512 512


In [54]:
print('평균:', np.mean(array), array.mean())

평균: 51.2 51.2


In [55]:
print('분산:', np.var(array), array.var())

분산: 1161.3600000000001 1161.3600000000001


In [56]:
print('표준편차:', np.std(array), array.std())

표준편차: 34.07873237079102 34.07873237079102


In [57]:
print('최댓값:', np.max(array), array.max())

최댓값: 98 98


In [58]:
print('최솟값:', np.min(array), array.min())

최솟값: 5 5


In [60]:
print('중앙값:', np.median(array))  # 중앙값은 메서드가 제공되지 않음.

중앙값: 52.0


## 2차원 배열에서의 통계 함수/매서드


In [67]:
np.random.seed(42)  # 실행할 때마다 같은 난수들을 생성하기 위해서.
array = np.random.randint(10, size=(5, 4))
print(array)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]
 [1 7 5 1]]


In [68]:
np.sum(array)  # 2차원의 배열의 모든 원소들의 합계

np.int64(96)

In [69]:
array.sum()

np.int64(96)

In [70]:
np.sum(array, axis=0)  # axis=0 축을 따라서 계산한 원소들의 합계

array([27, 25, 22, 22])

In [71]:
array.sum(axis=0)

array([27, 25, 22, 22])

In [72]:
np.sum(array, axis=1)  # axis=1 축을 따라서 계산한 원소들의 합계

array([20, 23, 21, 18, 14])

In [73]:
array.sum(axis=1)

array([20, 23, 21, 18, 14])

In [74]:
array.sum(axis=0, keepdims=True)  # (1, 4) shape의 2차원 배열

array([[27, 25, 22, 22]])

In [76]:
array.sum(axis=1, keepdims=True)  # (5, 1) shape의 2차원 배열

array([[20],
       [23],
       [21],
       [18],
       [14]])