In [1]:
import numpy as np
import pandas as pd

# Series 인덱스

## 단일 계층 인덱스

In [49]:
s = pd.Series(data=np.random.rand(5), name="rand_num")
#> Series 객체도 (데이터프레임의 컬럼처럼) 값들의 이름을 설정할 수 있음.
s

,rand_num
0,0.421052
1,0.140297
2,0.254185
3,0.346938
4,0.484798


In [5]:
s.index  #> Series 객체가 가지고 있는 index 속성

RangeIndex(start=0, stop=5, step=1)

In [6]:
s.values  #> Series 객체가 가지고 있는 values 속성 -> 값들을 아이템으로 갖는 1차원 ndarray(배열)

array([0.7396242 , 0.23342527, 0.01574426, 0.82605215, 0.70676605])

In [13]:
s.iloc[0:2]

,rand_num
0,0.739624
1,0.233425


In [15]:
s.loc[0:2]

,rand_num
0,0.739624
1,0.233425
2,0.015744


In [57]:
s.loc[0]  #> 인덱스 0 위치의 값

np.float64(0.4210517986611688)

In [58]:
s.loc[[0, 4]]  #> 인덱스 0, 4 위치의 값들

,rand_num
0,0.421052
4,0.484798


In [60]:
s = pd.Series(data=np.random.randint(100, size=5), name="score",
              index=["scott", "allen", "king", "홍길동", "오쌤"])

s

,score
scott,46
allen,12
king,92
홍길동,13
오쌤,86


In [17]:
s.index

Index(['scott', 'allen', 'king', '홍길동', '오쌤'], dtype='object')

In [18]:
s.values

array([21,  1, 59, 25,  4])

In [19]:
s.iloc[-1]

np.int64(4)

In [24]:
# s.loc[-1] -> error
s.loc["오쌤"]

np.int64(4)

In [25]:
s.loc["scott":"king"]

,score
scott,21
allen,1
king,59


In [28]:
s.index.nlevels  # 인덱스의 레벨(계층) 개수

1

In [61]:
s.loc["홍길동"]  #> 해당 인덱스의 값 1개

np.int64(13)

In [62]:
s.loc[["scott", "홍길동"]]

,score
scott,46
홍길동,13


## 계층적 인덱스(hierachical index), multi-level index

In [71]:
s = pd.Series(data=np.random.randint(100, size=6), name="score",
              index=[["m", "m", "m", "f", "f", "f"], ["a", "b", "c", "a", "b", "c"]])

s

m  a    96
   b     4
   c    30
f  a    89
   b     9
   c     5
Name: score, dtype: int64

In [32]:
s.values  #> 1차원 배열(ndarray)

array([19, 94, 56, 71, 76, 98])

In [33]:
s.index  #> MultiIndex - 튜플들을 아이템으로 갖는 배열

MultiIndex([('m', 'a'),
            ('m', 'b'),
            ('m', 'c'),
            ('f', 'd'),
            ('f', 'e'),
            ('f', 'f')],
           )

In [36]:
s.index.nlevels  #> 2

2

In [37]:
s.iloc[-1]

np.int64(98)

### Multi-level index에서 indexing, slicing

nlevels(인덱스의 계층 개수)가 2개 이상인 multi-level 인덱스를 loc 속성에서 사용할 때,
*   첫번째 계층(level)의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층의 인덱스만 가지고는 indexing/slicing을 할 수 없음!
*   튜플 형태의 인덱스로 indexing/slicing을 할 수 있음.


In [38]:
s

m  a    19
   b    94
   c    56
f  d    71
   e    76
   f    98
Name: score, dtype: int64

In [39]:
s.loc["m"]  # 첫번째 계층(level)의 인덱스로 indexing.

,score
a,19
b,94
c,56


In [65]:
s.loc["f"]

,score
d,69
e,93
f,37


In [67]:
# s.loc["a"] --> Error  #> KeyError - "a"는 첫번째 계층(level)의 인덱스가 아니기 때문에.
s.loc[("m", "a")]  #> 튜플 형태의 인덱스를 사용한 indexing.

np.int64(47)

In [72]:
s.loc[[("m", "a"), ("f", "a")]]

,,score
m,a,96
f,a,89


In [73]:
s_idx_sorted = s.sort_index()
s_idx_sorted

f  a    89
   b     9
   c     5
m  a    96
   b     4
   c    30
Name: score, dtype: int64

In [76]:
s_idx_sorted.loc["f":"m"]  #> slicing은 인덱스들이 정렬된 상태일 때 가능.

f  a    89
   b     9
   c     5
m  a    96
   b     4
   c    30
Name: score, dtype: int64

In [77]:
s_idx_sorted.loc[("f", "a"):("m", "a")]

f  a    89
   b     9
   c     5
m  a    96
Name: score, dtype: int64

*   `pd.Series.sort_index()`: 인덱스를 정렬.
*   `pd.Series.sort_values()`: 값들을 정렬.
*   `inplace` 파라미터:
    *   `inplace=True`: 원본 Series를 정렬된 상태로 변경.
    *   `inplace=False`: 기본값. 원본은 수정되지 않고, 정렬된 새로운 Series 객체를 리턴.

In [78]:
np.random.seed(42)
s = pd.Series(data=np.random.rand(5), index=["b", "a", "z", "d", "c"])
s

,0
b,0.374540
a,0.950714
z,0.731994
d,0.598658
c,0.156019


In [79]:
s.sort_values()

,0
c,0.156019
b,0.374540
d,0.598658
z,0.731994
a,0.950714


In [81]:
s  #> 원본 Series는 값들이 정렬되어 있지 않음.

,0
b,0.374540
a,0.950714
z,0.731994
d,0.598658
c,0.156019


In [83]:
s.sort_values(inplace=True)  #> inplace=True: 원본 변경. 리턴 값은 없음.

In [ ]:
s  #> 원본 Series가 값들 오름차순 정렬된 상태.

In [84]:
s.sort_index()  #> inplace=False: 기본값. 인덱스들이 정렬된 Series를 리턴.

,0
a,0.950714
b,0.374540
c,0.156019
d,0.598658
z,0.731994


In [ ]:
s  #> 원본은 변경 없음.

In [86]:
s.sort_index(inplace=True)  #> inplace=True: 원본 Series의 인덱스를 정렬. 리턴 값은 없음.z

In [87]:
s

,0
a,0.950714
b,0.374540
c,0.156019
d,0.598658
z,0.731994


### index swapping

multi-level 인덱스에서 인덱스의 레벨을 바꿈.

In [90]:
np.random.seed(42)
s = pd.Series(data=np.random.randint(100, size=6),
              index=[["m"]*3 + ["f"]*3, ["a", "b", "c"]*2])

s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [91]:
s.swaplevel()  # copy=True: 기본값. 원본은 변경 없음.

,,0
a,m,51
b,m,92
c,m,14
a,f,71
b,f,60
c,f,20


In [100]:
s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [102]:
# nlevels=3인 인덱스를 갖는 Series
np.random.seed(42)
s = pd.Series(data=np.random.rand(6),
              index=[np.arange(1, 7),
                    ["A"]*3 + ["B"]*3,
                    ["a", "b", "c"]*2])

s

,,,0
1,A,a,0.374540
2,A,b,0.950714
3,A,c,0.731994
4,B,a,0.598658
5,B,b,0.156019
6,B,c,0.155995


In [103]:
s.swaplevel()  # i=-2, j=-1: 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

,,,0
1,a,A,0.374540
2,b,A,0.950714
3,c,A,0.731994
4,a,B,0.598658
5,b,B,0.156019
6,c,B,0.155995


In [104]:
s.swaplevel(i=0, j=1)  #> 첫번째 인덱스와 두번째 인덱스를 바꿈.

A  1  a    0.374540
   2  b    0.950714
   3  c    0.731994
B  4  a    0.598658
   5  b    0.156019
   6  c    0.155995
dtype: float64

# DataFrame 인덱스

In [110]:
np.random.seed(42)
df = pd.DataFrame(data=np.random.randint(100, size=(6, 3)),
                  columns=["total_bill", "tip", "size"],
                  index=[["Fri", "Fri", "Sat", "Sat", "Sun", "Sun"], ["Lunch", "Dinner"]*3])

df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [ ]:
df.values  #> DataFrame의 값들로 이루어진 2차원 배열(ndarray)

In [ ]:
df.columns  #> 컬럼 이름(인덱스)들로 이루어진 배열

In [108]:
df.index  #> multi-level 인덱스: 튜플들의 배열

MultiIndex([('Fir',  'Lunch'),
            ('Fir', 'Dinner'),
            ('Sat',  'Lunch'),
            ('Sat', 'Dinner'),
            ('Sun',  'Lunch'),
            ('Sun', 'Dinner')],
           )

In [111]:
df.loc["Fri"]  #> 첫번째 인덱스만 가지고도 indexing

,total_bill,tip,size
Lunch,51,92,14
Dinner,71,60,20


In [112]:
df.loc[("Fri", "Dinner")]  # 첫번째, 두번째 계층의 인덱스들을 모두 사용한 indexing

,Fri
,Dinner
total_bill,71
tip,60
size,20


In [113]:
df.loc[["Sat", "Sun"]]

total_bill  tip  size
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [114]:
df.loc[[("Fri", "Lunch"), ("Sat", "Lunch"), ("Sun", "Lunch")]]

,,total_bill,tip,size
Fri,Lunch,51,92,14
Sat,Lunch,82,86,74
Sun,Lunch,23,2,21


In [ ]:
df.loc["Lunch"]  #> KeyError - "Lunch"는 첫번째 계층(level)의 인덱스가 아니기 때문에.

In [115]:
df.loc["Fir":"Sat"]

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99

In [122]:
df.index.nlevels

2

In [123]:
df.swaplevel()  # i=-2, j=-1: 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

,,total_bill,tip,size
Lunch,Fri,51,92,14
Dinner,Fri,71,60,20
Lunch,Sat,82,86,74
Dinner,Sat,74,87,99
Lunch,Sun,23,2,21
Dinner,Sun,52,1,87


In [126]:
df.swaplevel().loc["Lunch"]

,total_bill,tip,size
Fri,51,92,14
Sat,82,86,74
Sun,23,2,21


## DataFrame 컬럼 <---> DataFrame인덱스

*   `pd.DataFrame.set_index()`: 데이터프레임의 컬럼(들)을 인덱스로 변환.
*   `pd.DataFrame.reset_index()`: 인덱스를 데이터프레임의 컬럼으로 변환.

In [127]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [128]:
df.reset_index()  # 기본 동작: 모든 level의 인덱스를 컬럼으로 변환.

,level_0,level_1,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [130]:
# 인덱스를 컬럼으로 변환할 때 사용할 컬럼 이름들을 설정.
df.reset_index(names=["day", "time"])

,day,time,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [133]:
df.reset_index(level=0, names="day")

,day,total_bill,tip,size
Lunch,Fri,51,92,14
Dinner,Fri,71,60,20
Lunch,Sat,82,86,74
Dinner,Sat,74,87,99
Lunch,Sun,23,2,21
Dinner,Sun,52,1,87


In [144]:
df.reset_index(level=1, names=[None, "time"])  #> None이든 1이든 뭐 상관이 없음. 걍 위치만 맞춰주면 됨.

,time,total_bill,tip,size
Fri,Lunch,51,92,14
Fri,Dinner,71,60,20
Sat,Lunch,82,86,74
Sat,Dinner,74,87,99
Sun,Lunch,23,2,21
Sun,Dinner,52,1,87


## `set_index`

In [145]:
exam = pd.DataFrame(data={
    "class": [1] * 5 + [2] * 5,
    "id": np.arange(1, 11),
    "math": np.random.randint(100, size=10),
    "science": np.random.randint(100, size=10)
})

exam

,class,id,math,science
0,1,1,29,88
1,1,2,37,48
2,1,3,1,90
3,1,4,63,58
4,1,5,59,41
5,2,6,20,91
6,2,7,32,59
7,2,8,75,79
8,2,9,57,14
9,2,10,21,61


In [146]:
# class = 1 인 데이터 선택
exam[exam["class"] == 1]

,class,id,math,science
0,1,1,29,88
1,1,2,37,48
2,1,3,1,90
3,1,4,63,58
4,1,5,59,41


In [147]:
exam_cls = exam.set_index(keys=["class"])
exam_cls

,id,math,science
class,,,
1,1,29,88
1,2,37,48
1,3,1,90
1,4,63,58
1,5,59,41
2,6,20,91
2,7,32,59
2,8,75,79
2,9,57,14


In [154]:
exam_cls.loc[1]

,id,math,science
class,,,
1,1,29,88
1,2,37,48
1,3,1,90
1,4,63,58
1,5,59,41


In [156]:
exam.set_index(keys=["class", "id"])

math  science
class id               
1     1     29       88
      2     37       48
      3      1       90
      4     63       58
      5     59       41
2     6     20       91
      7     32       59
      8     75       79
      9     57       14
      10    21       61

In [158]:
exam.set_index(keys=["id", "class"])

,,math,science
id,class,,
1,1,29,88
2,1,37,48
3,1,1,90
4,1,63,58
5,1,59,41
6,2,20,91
7,2,32,59
8,2,75,79
9,2,57,14


,,math,science
id,class,,
1,1,29,88
2,1,37,48
3,1,1,90
4,1,63,58
5,1,59,41
6,2,20,91
7,2,32,59
8,2,75,79
9,2,57,14
