# Numpy

In [3]:
import numpy as np

# `numpy.ndarray` 클래스 속성들(properties)

In [4]:
# 2차원 배열(2-dimensional array)
arr = np.ones(shape=(2, 3))  #> 모든 원소가 1인 배열

In [5]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소 개수들의 튜플(tuple)

(2, 3)

In [7]:
arr.size  # size 속성: 배열의 모든 원소 개수

6

In [8]:
arr.ndim  # ndim 속성: 배열의 차원 개수. 축(axis)의 개수.

2

In [9]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타임(data type)

dtype('float64')

In [10]:
# 1차원 배열(1-dimensional array)
arr = np.arange(10)
print(arr)
print("shape:", arr.shape)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
size: 10
ndim: 1
dtype: int64


In [11]:
# 3차원 배열(3-dimensional array)
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
print("shape:", arr.shape)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [13]:
print(arr)  #> 3d array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
print(arr[0])  # 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0][0])  # 1d array

[1 2 3 4]


In [16]:
print(arr[0, 0])

[1 2 3 4]


In [17]:
print(arr[0][0][0])  #> 값(int) --> scalar

1


In [18]:
print(arr[0, 0, 0])

1


*   Python list 인덱스 사용 방법:
        *   `list[i][j][k]...`
*   Numpy ndarray 인덱스 사용 방법:
    *   `array[i][j][k]...`
    *   `array[i, j, k, ...]`

# Slicing

배열을 잘라서 새로운 배열을 만듦.

## 1d array의 slicing

In [19]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
print(arr[1:5])

[1 2 3 4]


In [21]:
print(arr[:3])  # 시작 인덱스 0은 생략 가능

[0 1 2]


In [22]:
print(arr[-3:])  # 배열의 끝까지 자를 때는 마지막 인덱스를 생략할 수 있음.

[7 8 9]


In [23]:
print(arr[0:1])  # slicing  --> 배열(ndarray)
print(arr[0])  # indexing  --> 배열의 원소ㅠ

[0]
0


## 2d array의 slicing

In [24]:
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [28]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [29]:
print(arr[:3, :2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [30]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
print(arr[:3][:2])  # arr[:3, :2]의 결과와 다름!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 3d array의 slicing

In [32]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [33]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [34]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [35]:
print(arr[:2, :2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [36]:
print(arr[:2, :2, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [37]:
print(arr[:2, :2, :2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [38]:
print(arr[:1, :, :])  #> 3d array

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [39]:
print(arr[0, :, :])  # 2d array. arr[:1, :, :]와 다름!

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# 배열 모양(shape) 변경

*   `reshape()`
*   `ravel()`
*   `flatten()`
*   `np.newaxis` 속성


In [40]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
# arr_1d를 (4, 3) shape의 2d array로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
# reshape 메서드에 아규먼트를 전달할 때, 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음. (걍 -213451345 이래도 상관 없음. 짜피 자동으로 결정이 됨 0 이상만 아니면 되는듯)
arr_2d = arr_1d.reshape((4, -1))  # (4, 3) (4, -24165234636)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
arr_2d = arr_1d.reshape((-1, 4))  # (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
arr_1d = np.arange(24)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [45]:
# arr_1d (2, 3, 4) 모양의 3d array로 변환
arr_3d = arr_1d.reshape((2, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [46]:
arr_3d = arr_1d.reshape((2, 3, -1))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [47]:
arr_3d = arr_1d.reshape((-1, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## ravel vs flatten

*   ravel
    *   n차원 배열을 1차원 배열로 변환한 "뷰(view)"를 리턴.
    *   새로운 1차원 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원처럼 보여줄 뿐.
    *   리턴된 1차원 배열에서 원소를 변경하면, 원본 배열도 변경됨!
*   flatten
    *   n차원 배열을 1차원 배열로 변환한 "복사본"을 리턴.
    *   원본 배열과는 별개의 새로운 1차원 배열을 메모리에 만들어서 리턴.
    *   리턴된 1차원 배열의 원소를 변경하는 것은 원본 배열에 영향을 주지 않음!

In [48]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
flattened = arr_2d.flatten()  # 2d --> 1d
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
flattened[0] = 123
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [51]:
print(arr_2d)  # 원본 2d array는 변경되지 않음.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
raveled = arr_2d.ravel()  # 2d --> 1d
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
raveled[0] = 123
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [54]:
print(arr_2d)  # 원본 2d array이 변경됨!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [55]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [56]:
arr.shape

(6,)

In [57]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4 5]]


In [58]:
result.shape

(1, 6)

In [59]:
print(arr.reshape(1, -1))

[[0 1 2 3 4 5]]


In [60]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [61]:
result.shape

(6, 1)

In [62]:
print(arr.reshape(-1, 1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


# 배열 합치기(concatenate)

*   `np.concatenate([array1, array2, ...], axis=0)`: 특정 축(axis) 방향으로 배열 이어붙이기.

*   `np.r_[array1, array2]`: 행들을 이어붙이기. axis=0 방향으로 이어붙이기.
*   `np.c_[array1, array2]`: 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.

In [63]:
# (2, 3) shape의 2d array
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [64]:
# (1, 3) shape의 2d array
arr2 = np.array([[10, 20, 30]])
print(arr2)

[[10 20 30]]


In [65]:
# (2, 1) shape의 2d array
arr3 = np.array([[11], [12]])
print(arr3)

[[11]
 [12]]


In [66]:
result = np.concatenate([arr1, arr2])  # axis=0(기본값) 생략 가능
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


In [67]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[ 0  1  2 11]
 [ 3  4  5 12]]


In [68]:
np.r_[arr1, arr2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [69]:
np.c_[arr1, arr3]

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 12]])

In [70]:
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [71]:
arr2 = np.array([10, 20, 30])

In [72]:
# np.concatenate([arr1, arr2], axis=0)
#> ValueError 발생. 차원이 다르면 concatenate가 되지 않음.

# Broadcasting

*   numpy.ndarray의 연산(+, -, *, /, ==, !=, >, <, ...)은 같은 인덱스(위치)의 원소들(element-wise)끼리 연산이 수행됨.
*   서로 모양(shape)이 다른 배열끼리도 element-wise 연산이 가능한 경우가 있음 --> broadcast
*   broadcasting이 가능한 경우
    *   누락되었거나 길이가 1인 차원에 대해서 broadcasting이 수행.
    *   이어지는 차원의 축의 길이가 같은 경우에 broadcasting이 가능.

## ndarray와 scalar의 연산

항상 연산이 가능(항상 브로드캐스트가 가능). 스칼라를 배열의 각 원소마다 연산 수행.

In [73]:
a = np.array([1, 2, 3])
print(a)
print(a + 10)

[1 2 3]
[11 12 13]


## 2d array와 2d array의 broadcast

In [75]:
a = np.arange(1, 7).reshape((2, 3))  # shape: (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [76]:
b = np.array([[7, 8, 9]])  #shape: (1, 3)
print(b)

[[7 8 9]]


In [77]:
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [79]:
c = np.array([[11],[12]])  # shape: (2, 1)
print(c)

[[11]
 [12]]


In [80]:
print(a + c)

[[12 13 14]
 [16 17 18]]


## 2d array와 1d array의 broadcast

In [82]:
print(a)

[[1 2 3]
 [4 5 6]]


In [83]:
d = np.array([7, 8, 9])  # shape: (3,)
print(d)

[7 8 9]


In [84]:
print(a+b)

[[ 8 10 12]
 [11 13 15]]


In [85]:
e = np.array([7, 8])  # shape: (2,)
print(e)

[7 8]


In [86]:
# print(a+e)
#> ValueError 발생: (2, 3)과 (2,) 모양의 배열들은 브로드캐스트가 불가능.

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## broadcast 활용

*   표준화(standardization): 평균이 0이 되고 표준편차가 1이 되도록 값들을 변환.
>   $$z = \dfrac{x - \mu}{\sigma}$$
*   정규화(normalization): 최소값이 0이 되고 최댓값이 1이 되도록 값들을 변환.
>   $$x_{norm} = \dfrac{x - x_{min}}{x_{max} - x_{min}}$$


### 1차원 배열 표준화

In [87]:
x = np.arange(1, 6)
print(x)

[1 2 3 4 5]


In [92]:
mu = x.mean()  # 평균
print(mu)

3.0


In [93]:
sigma = x.std()  # 표준편차(standard deviation)
print(sigma)

1.4142135623730951


In [94]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [96]:
print(x_scaled.mean())
print(x_scaled.std())

0.0
0.9999999999999999


### 1차원 배열 정규화

In [97]:
print(x)

[1 2 3 4 5]


In [98]:
x_norm = (x - x.min()) / (x.max() - x.min())
x_norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 2차원 배열에서의 표준화

In [99]:
x = np.arange(1, 13).reshape((4, 3))
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
mu = x.mean()  # 파라미터 axis=None인 경우, 모든 원소(스칼라)들의 평균
print(mu)

6.5


In [102]:
sigma = x.std() # 파라미터 axis=None인 경우, 모든 원소(스칼라)들의 표준편차
print(sigma)

3.452052529534663


In [103]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[[-1.59325501 -1.30357228 -1.01388955]
 [-0.72420682 -0.43452409 -0.14484136]
 [ 0.14484136  0.43452409  0.72420682]
 [ 1.01388955  1.30357228  1.59325501]]


In [114]:
# axis=0 축 방향으로 평균을 계산
mu = x.mean(axis=0)
print(mu)  # mu shape: (3,) if, keepdims=True, then shape: (1, 3)

[5.5 6.5 7.5]


In [105]:
# axis=0 축 방향으로 표준편차들을 계산
sigma = x.std(axis=0)
print(sigma)  # sigma shape: (3,)

[3.35410197 3.35410197 3.35410197]


In [106]:
# axis=0 축 방향으로 값들을 표준화
x_scaled = (x - mu) / sigma
print(x_scaled)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


In [110]:
# axis=1 축 방향으로 평균들을 계산
mu = x.mean(axis=1, keepdims=True)
print(mu)  # shape (4, 1)

[[ 2.]
 [ 5.]
 [ 8.]
 [11.]]


In [109]:
x - mu

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [111]:
# axis=1 축 방향으로 표준편차들을 계산
sigma = x.std(axis=1, keepdims=True)
print(sigma)

[[0.81649658]
 [0.81649658]
 [0.81649658]
 [0.81649658]]


In [112]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


In [117]:
# 2차원 배열의 정규화
(x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

In [119]:
# 2차원 배열의 정규화 (2)
(x - x.min(axis=1, keepdims=True)) / (x.max(axis=1, keepdims=True) - x.min(axis=1, keepdims=True))


array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])