# ANN(Artificial Neural Network, 인공신경망)

# Imports

In [1]:
from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

In [3]:
tf.__version__

'2.19.0'

In [4]:
keras.__version__

'3.13.2'

# Iris 데이터셋

In [5]:
data, target = datasets.load_iris(return_X_y=True)

In [6]:
data.shape

(150, 4)

In [7]:
target.shape

(150,)

In [8]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [13]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 이진 분류(binary classification)


*   2개의 특성만을 사용
*   0(setosa)과 0이 아닌(versicolor, virginica)

In [11]:
x = data[:, :2]

In [12]:
x[:5]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [16]:
y = (target != 0).astype('int')
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## SGD Classifier(확률적 경사하강법 분류기)

In [17]:
# loss='log_loss': logistic 손실 함수를 최소화하는 확률적 경사 하강법. 확률 -> 분류.
# max_iter=10: epoch(모든 샘플을 사용해서 경사하강법을 수행) 횟수를 10번.
sgd = SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [20]:
sgd.fit(X=x, y=y)  # 모델 훈련 -> 손실함수를 최소로 만드는 가중치(절편과 계수들) 찾음.

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [21]:
sgd.coef_

array([[ 107.47482122, -163.79917975]])

In [22]:
sgd.intercept_

array([-53.41269101])

$
y = -53 + 107 x_1 -163 x_2
$

In [23]:
# SGD의 예측 확률
y_prob = sgd.predict_proba(X=x)

In [24]:
y_prob[:5]

array([[1.00000000e+00, 7.40567283e-35],
       [9.99999987e-01, 1.26753544e-08],
       [1.00000000e+00, 3.47056174e-32],
       [1.00000000e+00, 9.69472704e-30],
       [1.00000000e+00, 1.22541827e-46]])

In [25]:
y_prob[-5:]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [26]:
# SGD 모델의 예측값
y_pred = sgd.predict(X=x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
# SGD 모델의 정확도
accuracy_score(y_true=y, y_pred=y_pred)

0.9933333333333333

In [28]:
149/150

0.9933333333333333

# 신경망(Neural Network)

In [29]:
# 입력층(input layer)
inputs = keras.Input(shape=(2,))

In [30]:
# 출력층(output layer)
dense = keras.layers.Dense(units=1, activation='sigmoid')

In [31]:
# 신경망 모델 생성
model = keras.Sequential(layers=[inputs, dense])

In [32]:
# 생성된 신경망 모델 정보 요약
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
# 신경망 모델 컴파일: optimizer(최적화 알고리즘), loss(손실 함수), metrics(평가 기준)을 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [35]:
# 신경망 모델 훈련
model.fit(x=x, y=y, batch_size=1, epochs=10)

Epoch 1/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.7467 - loss: 0.6747  
Epoch 2/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8600 - loss: 0.3963
Epoch 3/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9133 - loss: 0.3644
Epoch 4/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.9333 - loss: 0.3345
Epoch 5/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.9533 - loss: 0.3116
Epoch 6/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9333 - loss: 0.2897
Epoch 7/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9733 - loss: 0.2689  
Epoch 8/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9733 - loss: 0.2560  
Epoch 9/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9800 - loss: 0.2450  
Epoch 10/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9667 - loss: 0.2354  


In [36]:
# 신경망 모델이 학습을 통해서 찾은 모델 파라미터들(가중치, weights)
model.weights

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[ 1.4281981]
  [-2.1980882]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[-0.362179]>]

In [39]:
# 신경망 모델의 예측값
y_pred = model.predict(x=x)
y_pred.shape  #> (n_samples, 1): 150개 샘플들의 양성(1)일 예측 확률

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


(150, 1)

In [40]:
y_pred[:5]

array([[0.31611633],
       [0.5104303 ],
       [0.33547375],
       [0.3528487 ],
       [0.24336727]], dtype=float32)

In [41]:
y_pred[-5:]

array([[0.93166065],
       [0.9585228 ],
       [0.911076  ],
       [0.73480684],
       [0.81304604]], dtype=float32)

In [42]:
y_pred_label = (y_pred > 0.5).astype("int").ravel()
y_pred_label

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
# 신경망 모델 평가
model.evaluate(x=x, y=y)  #> [loss, accuracy]

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.9800 - loss: 0.2237  


[0.22370781004428864, 0.9800000190734863]

# 은닉층(hidden layer)을 가지고 있는 신경망

In [44]:
inputs = keras.layers.Input(shape=(2,))  # 입력층
dense1 = keras.layers.Dense(units=2, activation='sigmoid')  # 은닉층
dense2 = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층

In [45]:
model = keras.Sequential(layers=[inputs, dense1, dense2])  # 신경망

In [46]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
# 모델 컴파일: 어떤 손실함수를 어떤 평가 기준으로 어떻게 최적화할 것인가를 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [52]:
# 모델 훈련
model.fit(x=x, y=y, batch_size=30, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - binary_accuracy: 0.6667 - loss: 0.6369
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - binary_accuracy: 0.6667 - loss: 0.6368 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - binary_accuracy: 0.6667 - loss: 0.6369
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.6667 - loss: 0.6368 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.6667 - loss: 0.6368 
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.6667 - loss: 0.6368  
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.6667 - loss: 0.6368  
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.6667 - loss: 0.6368 
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.6667 - loss: 0.6368
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.6667 - loss: 0.6368 


In [49]:
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(2, 2), dtype=float32, value=[[-0.87843484 -1.0574464 ]
  [-0.5605762  -0.1390895 ]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(2,), dtype=float32, value=[ 0.00062352 -0.00398766]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(2, 1), dtype=float32, value=[[-0.26593754]
  [ 0.604884  ]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(1,), dtype=float32, value=[0.66615176]>]

In [50]:
model.evaluate(x=x, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - binary_accuracy: 0.6667 - loss: 0.6368     


[0.6368316411972046, 0.6666666865348816]

# SGD

4개의 특성을 모두 사용한 다중 클래스(0/1/2) 분류

In [55]:
sgd = SGDClassifier(loss='log_loss', n_jobs=-1, random_state=42)  # max_iter=1_000

In [56]:
# data: (150, 4), target: (150,)
sgd.fit(X=data, y=target)  # 모델 훈련

SGDClassifier(loss='log_loss', n_jobs=-1, random_state=42)

In [57]:
sgd.coef_  #> (3, 4)

array([[   7.32064421,   13.17715959,  -27.57442655,  -12.68911664],
       [  36.72801312,  -95.62396704,   33.04272408,  -96.76701144],
       [-123.44647495, -105.30456435,  149.42075067,  157.58173689]])

In [58]:
sgd.intercept_  #> (3,)

array([   4.97012943,  128.91629652, -130.52603923])

In [59]:
y_prob = sgd.predict_proba(X=data)

In [60]:
y_prob.shape #> (150, 3)

(150, 3)

In [61]:
y_prob[:5]

array([[0.50005338, 0.49994662, 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.9917711 , 0.0082289 , 0.        ]])

In [62]:
y_pred = sgd.predict(X=data)

In [64]:
y_pred[:5]

array([0, 1, 0, 0, 0])

In [65]:
accuracy_score(y_true=target, y_pred=y_pred)

0.62

# 신경망

4개 특성을 모두 사용한 다중 클래스(0/1/2) 분류

In [86]:
model = keras.Sequential()  # Sequential(완전 연결 신경망)

In [87]:
# 신경망에 입력층을 추가
model.add(keras.layers.Input(shape=(4,)))

In [88]:
# 신경망에 출력층을 추가
model.add(keras.layers.Dense(units=3, activation='softmax'))

In [89]:
model.summary()
#> # of params = 4 features * 3 units + 3 bias = 15

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [90]:
# 모델 컴파일
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.sparse_categorical_crossentropy,
              metrics=[keras.metrics.sparse_categorical_accuracy])

In [91]:
# 모델 훈련
model.fit(x=data, y=target, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8353 - sparse_categorical_accuracy: 0.6200  
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1231 - sparse_categorical_accuracy: 0.6533
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4988 - sparse_categorical_accuracy: 0.6667 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0884 - sparse_categorical_accuracy: 0.6667 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9448 - sparse_categorical_accuracy: 0.5533 
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8988 - sparse_categorical_accuracy: 0.3800 
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8814 - sparse_categorical_accuracy: 0.4067 
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8613 - sparse_categorical_accuracy: 0.4467 
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8422 - sparse_categorical_accuracy: 0.4133 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8261 - sparse_categor

In [93]:
model.weights
#> kernel: (4, 3)
#> bias: (3,)

[<Variable path=sequential_4/dense_6/kernel, shape=(4, 3), dtype=float32, value=[[-0.10972992  0.12164837  0.27440655]
  [ 0.18057895 -0.68767244 -0.6897115 ]
  [ 0.28292066  0.5207159   0.45091772]
  [-0.01503189  0.5430801   0.13176656]]>,
 <Variable path=sequential_4/dense_6/bias, shape=(3,), dtype=float32, value=[-0.0176674  -0.02249197  0.04015936]>]

In [94]:
predicts = model.predict(x=data)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


In [95]:
predicts.shape  #> (n_samples, n_classes)

(150, 3)

In [96]:
predicts[:5]

array([[0.5856615 , 0.14168449, 0.27265403],
       [0.49438614, 0.17627186, 0.329342  ],
       [0.5589257 , 0.15618198, 0.28489226],
       [0.5359906 , 0.16739702, 0.29661235],
       [0.6144795 , 0.13317624, 0.25234437]], dtype=float32)

In [97]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8136 - sparse_categorical_accuracy: 0.3800  


[0.8135918974876404, 0.3799999952316284]

In [98]:
# epoch 횟수를 증가시켜서 훈련
model.fit(x=data, y=target, epochs=1_000, verbose=0)

In [99]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1751 - sparse_categorical_accuracy: 0.9733 


[0.17511828243732452, 0.9733333587646484]

# 은닉층을 갖는 신경망

*   4개 특성, 3개 클래스 분류
*   입력층 --> 은닉층 --> 출력층
*   은닉층: 8개 unit, 활성화 함수 relu

In [111]:
model = keras.Sequential()

In [112]:
model.add(keras.layers.Input(shape=(4,)))
model.add(keras.layers.Dense(units=8, activation='relu'))
model.add(keras.layers.Dense(units=3, activation='relu'))

In [113]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

In [114]:
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.sparse_categorical_crossentropy,
              metrics=[keras.metrics.sparse_categorical_accuracy])

In [115]:
model.fit(x=data, y=target, epochs=100, verbose=False)

In [116]:
model.weights

[<Variable path=sequential_6/dense_9/kernel, shape=(4, 8), dtype=float32, value=[[ 0.57050747 -0.22400948  0.23181623 -0.46747142  0.18217164 -0.28119603
    0.30023986 -0.22013754]
  [ 0.64487153  0.00621986 -0.34349006 -0.26120257 -0.5678539   0.21984994
    0.23260677  0.18824148]
  [-0.209001   -0.4801283  -0.25036305 -0.43452457 -0.12079757  0.18371391
    0.5181981  -0.5762172 ]
  [-0.16664529  0.20964903 -0.22056237 -0.4927609  -0.49696428  0.02589589
    0.45143443  0.20548475]]>,
 <Variable path=sequential_6/dense_9/bias, shape=(8,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0.]>,
 <Variable path=sequential_6/dense_10/kernel, shape=(8, 3), dtype=float32, value=[[ 0.1680072  -0.4027714  -0.1654436 ]
  [-0.44109166 -0.7179146  -0.13705939]
  [ 0.37224215 -0.5200707   0.00979662]
  [ 0.6450333  -0.08906299 -0.371198  ]
  [-0.72489154  0.07596201  0.59841174]
  [-0.3986514  -0.109083    0.53990144]
  [ 0.24132901  0.20072299 -0.6899232 ]
  [ 0.29693168 -0.58668476  0.58498544]]>,

In [117]:
predicts = model.predict(x=data)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [118]:
predicts.shape

(150, 3)

In [119]:
predicts[:5]

array([[1.5761416, 0.       , 0.       ],
       [1.4602416, 0.       , 0.       ],
       [1.4504815, 0.       , 0.       ],
       [1.4351916, 0.       , 0.       ],
       [1.5757588, 0.       , 0.       ]], dtype=float32)

In [120]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.7454 - sparse_categorical_accuracy: 0.3333     


[10.745397567749023, 0.3333333432674408]

In [121]:
# 강사님 답안

In [122]:
model = keras.Sequential()

In [123]:
# 입력층
model.add(keras.layers.Input(shape=(4,)))

In [124]:
# 은닉층
model.add(keras.layers.Dense(units=8, activation='relu'))

In [125]:
# 출력층
model.add(keras.layers.Dense(units=3, activation='softmax'))

In [126]:
model.summary()
# 은닉층 파라미터 개수 = 4 * 8 + 8 = 40
# 출력층 파라미터 개수 = 8 * 3 + 3 = 27

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

In [128]:
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.sparse_categorical_crossentropy,
              metrics=[keras.metrics.sparse_categorical_accuracy])

In [129]:
model.fit(x=data, y=target, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 1.3405 - sparse_categorical_accuracy: 0.3333 
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1577 - sparse_categorical_accuracy: 0.3333
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0807 - sparse_categorical_accuracy: 0.3467 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0494 - sparse_categorical_accuracy: 0.4533 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0417 - sparse_categorical_accuracy: 0.5600
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0341 - sparse_categorical_accuracy: 0.5467
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0271 - sparse_categorical_accuracy: 0.5667
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0201 - sparse_categorical_accuracy: 0.5733 
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0123 - sparse_categorical_accuracy: 0.6133 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0061 - sparse_categ

In [130]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0005 - sparse_categorical_accuracy: 0.6000  


[1.0005311965942383, 0.6000000238418579]