# Numpy

*   행렬 연산을 가능하게 해주는 패키지
*   python으로 작성되나 연산은 c, c++, 포트란으로 진행
    *   선형대수 연산을 빠르게 할 수 있음

In [16]:
import numpy as np

In [2]:
ary = np.array([1, 2, 3])
ary, type(ary)

(array([1, 2, 3]), numpy.ndarray)

*   `ndarray`: 한가지 데이터 타입만으로 사용이 가능 (데이터가 int, float, boolean, string 타입의 형태가 동일해야 한다는 것))

In [5]:
ary2 = np.array([[1, 2, 3], [4, 5, 6]])
ary2, ary2.ndim, ary2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [4]:
ary.shape  # 1차원 데이터

(3,)

In [6]:
ary2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
ary2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 행 선택
ary2[1]

array([4, 5, 6])

In [13]:
ary2[1, 1]

np.int64(5)

## 데이터 수정

In [14]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [18]:
ary3 = np.array([[1, 2, 3], [0, 0, 0]])
ary3[1, 1] = 1
ary3

array([[1, 2, 3],
       [0, 1, 0]])

In [20]:
ary3[1] = [1, 2, 3]
ary3

array([[1, 2, 3],
       [1, 2, 3]])

## array 브로드캐스팅
*   차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것

In [21]:
ary3[0] = 0
ary3

array([[0, 0, 0],
       [1, 2, 3]])

In [22]:
ls * 10

[1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3,
 1,
 5,
 3]

In [23]:
ary3 * 10

array([[ 0,  0,  0],
       [10, 20, 30]])

## array 조건 선택

In [24]:
ary3

array([[0, 0, 0],
       [1, 2, 3]])

In [25]:
ary3[0] = 5
ary3[1] = [3, 4, 5]
ary3

array([[5, 5, 5],
       [3, 4, 5]])

In [27]:
# mask 생성
idx = ary3 < 5
idx

array([[False, False, False],
       [ True,  True, False]])

In [28]:
ary3[idx]

array([3, 4])

## 조건에 맞는 값만 변경

In [29]:
ary3[idx] = 100
ary3

array([[  5,   5,   5],
       [100, 100,   5]])

## zero array

In [30]:
zero_ary = np.zeros((2, 3))
zero_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
type(zero_ary)

numpy.ndarray

In [33]:
zero_ary.dtype

dtype('float64')

## array안의 데이터 형태 변경

In [34]:
z2 = zero_ary.astype('int')
z2.dtype

dtype('int64')

In [35]:
z2

array([[0, 0, 0],
       [0, 0, 0]])

## one array

In [36]:
one_ary = np.ones((2, 3))
one_ary

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
one2 = one_ary.astype('int')
one2.dtype

dtype('int64')

In [38]:
one_ary2 = np.ones((2, 2, 3))
one_ary2

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
one_ary2.ndim

3

In [40]:
one_ary3 = np.ones((1, 2, 3))
one_ary3

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
one_ary3.shape, one_ary3.ndim

((1, 2, 3), 3)

In [42]:
one_ary4 = np.ones((2, 3))
one_ary4.shape, one_ary4.ndim

((2, 3), 2)

## 범위값 array 생성

In [47]:
ls2 = [i for i in range(1, 10 ,2)]
ls2

[1, 3, 5, 7, 9]

In [46]:
arg = np.arange(1, 11, 2)
arg

array([1, 3, 5, 7, 9])