# Numpy modules

In [1]:
import numpy as np

ary = [26, 25, 30, 34, 35, 44, 33, 45]
ary = np.array(ary)
ary

## Statistics modules
*   max, min, median, mean, std, var
*   cov, corrcoef

In [2]:
np.max(ary), np.min(ary), np.mean(ary), np.var(ary), np.std(ary)

(np.int64(45),
 np.int64(25),
 np.float64(34.0),
 np.float64(48.0),
 np.float64(6.928203230275509))

## linspace, logspace
*   linspace: 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
*   logspace: 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [3]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [5]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

### logspace
```
log10(x1) = 2, log_10(x_2) = 4
```

In [7]:
np.logspace(2, 6, 3)

array([1.e+02, 1.e+04, 1.e+06])

## numpy random module

*   seed: 랜덤의 설정값
*   rand: 균등분포로 난수 생성
*   randn: 정규분포로 난수 생성
*   randint: 균등분포로 정수 생성
*   shuffle: 섞기
*   choice: 데이터를 특정 확률로 뽑기

### seed

In [2]:
import random

In [3]:
np.random.seed(1)
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

### rand

In [4]:
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [5]:
np.random.rand(10)

array([0.4173048 , 0.55868983, 0.14038694, 0.19810149, 0.80074457,
       0.96826158, 0.31342418, 0.69232262, 0.87638915, 0.89460666])

In [6]:
np.random.rand(10)

array([0.08504421, 0.03905478, 0.16983042, 0.8781425 , 0.09834683,
       0.42110763, 0.95788953, 0.53316528, 0.69187711, 0.31551563])

In [8]:
np.random.seed(5)
res4 = np.random.rand(10)

# np.random.seed(6)
res5 = np.random.rand(10)

np.random.seed(5)
res6 = np.random.rand(10)

res4, res5, res6

(array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
        0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123]),
 array([0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703,
        0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781]),
 array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
        0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123]))

### randn

In [15]:
np.random.randn(10)

array([-2.85968797,  0.7893664 , -1.87774088,  1.53875615,  1.82136474,
       -0.42703139, -1.16470191, -1.39707402,  0.87265462, -0.20211818])

### randint

In [16]:
x = np.random.randint(1, 10, (4, 4))
x

array([[7, 9, 1, 2],
       [1, 9, 8, 8],
       [5, 2, 5, 3],
       [2, 8, 6, 5]])

In [18]:
x2 = np.random.randint(1, 10, (2, 4, 4))
x2

array([[[8, 4, 3, 7],
        [7, 3, 8, 1],
        [4, 8, 6, 2],
        [7, 8, 4, 8]],

       [[8, 7, 7, 5],
        [6, 5, 1, 1],
        [2, 6, 4, 2],
        [8, 1, 9, 4]]])

### shuffle

In [24]:
np.random.shuffle(x)
x

array([[7, 9, 1, 2],
       [5, 2, 5, 3],
       [2, 8, 6, 5],
       [1, 9, 8, 8]])