# numpy로 작성하는 행렬



기본적인 list 연산도 구현 가능?

In [1]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[4, 5, 6], [1, 2, 3]]
A + B  #?

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [1, 2, 3]]

list에서 요소들의 합 구현은 쉽지 않음

In [2]:
res = [[c + d for c, d in zip(a, b)] for a, b in zip (A, B)]
res

[[5, 7, 9], [5, 7, 9]]

In [3]:
import numpy as np
a = np.array(A)
b = np.array(B)
a + b

array([[5, 7, 9],
       [5, 7, 9]])

# 행렬의 곱

굳이 list로 만들어서 하겠다면...

In [9]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[6, 5], [4, 3], [2, 1]]
res = [[sum(a*b for a, b in zip (A_row, B_col)) for B_col in zip(*B)]for A_row in A]
res

[[20, 14], [56, 41]]

zip(*)

In [10]:
ls = [[1, 2, 3], [4, 5, 6]]
ls

[[1, 2, 3], [4, 5, 6]]

In [11]:
# Transpose
ls2 = list(map(list, zip(*ls)))
ls2

[[1, 4], [2, 5], [3, 6]]

## numpy 곱

In [15]:
import numpy as np
a = np.array(A)
b = np.array(B)

np.dot(a, b)  # = a@b

array([[20, 14],
       [56, 41]])

# 행렬 데이터의 결합
*   concatenate

In [16]:
r1 = np.array([[1, 9, 8], [7, 0, 2]])
r2 = np.array([[1, 8], [2, 2], [0, 2]])
r3 = np.array([[7, 6, 0], [3, 5, 4], [6, 7, 8]])

In [17]:
r1

array([[1, 9, 8],
       [7, 0, 2]])

In [18]:
r2

array([[1, 8],
       [2, 2],
       [0, 2]])

In [19]:
r3

array([[7, 6, 0],
       [3, 5, 4],
       [6, 7, 8]])

In [20]:
np.concatenate((r1, r3))

array([[1, 9, 8],
       [7, 0, 2],
       [7, 6, 0],
       [3, 5, 4],
       [6, 7, 8]])

In [21]:
np.concatenate((r2, r3), axis = 1)

array([[1, 8, 7, 6, 0],
       [2, 2, 3, 5, 4],
       [0, 2, 6, 7, 8]])

In [22]:
np.concatenate((r3, r2), axis = 1)

array([[7, 6, 0, 1, 8],
       [3, 5, 4, 2, 2],
       [6, 7, 8, 0, 2]])

In [23]:
ls1 = np.array([1, 2, 3])
ls2 = np.array([4, 5, 6])
np.c_[ls1, ls2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.r_[ls1, ls2]

array([1, 2, 3, 4, 5, 6])

# Quiz
*   위 행렬의 곱을 for문으로 작성하면?

In [29]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[6, 5], [4, 3], [2, 1]]
res = [[sum(a*b for a, b in zip (A_row, B_col)) for B_col in zip(*B)]for A_row in A]
res

[[20, 14], [56, 41]]

In [11]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[6, 5], [4, 3], [2, 1]]

sum_array= []
res = []
cal = 0

for A_row in A:
    sum_array = []
    for B_col in zip(*B):
        for a,b in zip(A_row, B_col):
            cal += a * b
        sum_array.append(cal)
        cal = 0

    res.append(sum_array)


print(res)


[[20, 14], [56, 41]]
